# Generated by Django 2.2 on 2022-09-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0004_auto_20220913_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
