# Generated by Django 2.2 on 2022-09-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0006_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
