# Generated by Django 2.2 on 2022-09-14 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0008_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='favorite_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
