# Generated by Django 2.2 on 2022-09-14 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0009_auto_20220914_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='favorite_users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
