# Generated by Django 2.2 on 2022-09-15 17:58

from django.db import migrations, models
import techcart.models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0013_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=techcart.models.upload_to),
        ),
    ]
