# Generated by Django 2.2 on 2022-09-15 18:24

from django.db import migrations, models
import techcart.models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0014_auto_20220915_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=techcart.models.upload_to),
        ),
    ]
