# Generated by Django 2.2 on 2022-09-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0015_userprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='forget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
