# Generated by Django 2.2 on 2022-09-20 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0016_forget'),
    ]

    operations = [
        migrations.CreateModel(
            name='catiegorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='techcart.product')),
            ],
        ),
    ]
