# Generated by Django 2.2 on 2022-09-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0017_catiegorys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catiegorys',
            name='products',
        ),
        migrations.AddField(
            model_name='catiegorys',
            name='products',
            field=models.ManyToManyField(blank=True, to='techcart.product'),
        ),
    ]
