# Generated by Django 2.2 on 2022-09-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0020_auto_20220921_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='orders',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='orders',
            field=models.ManyToManyField(null=True, to='techcart.order'),
        ),
    ]
