# Generated by Django 4.0.6 on 2022-12-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0026_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
        migrations.AddField(
            model_name='reviews',
            name='product',
            field=models.ManyToManyField(related_name='review', to='techcart.product'),
        ),
        migrations.DeleteModel(
            name='token',
        ),
    ]
