# Generated by Django 4.0.3 on 2022-12-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0027_remove_product_price_remove_product_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
