# Generated by Django 4.0.6 on 2023-01-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0029_remove_reviews_product_reviews_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Capacity',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Ram',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
