# Generated by Django 4.0.6 on 2023-01-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0035_remove_cart_product_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, to='techcart.product'),
        ),
    ]
