# Generated by Django 4.0.6 on 2023-01-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0036_remove_cart_product_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_option',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_method',
            field=models.TextField(null=True),
        ),
    ]
