# Generated by Django 4.0.6 on 2023-01-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0040_remove_cart_product_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorite_users',
        ),
    ]
