# Generated by Django 4.0.6 on 2023-01-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0043_remove_order_cart_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(to='techcart.cart'),
        ),
    ]
