# Generated by Django 4.0.6 on 2023-01-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0044_remove_cart_address_remove_cart_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='delivery_option',
        ),
    ]
