# Generated by Django 4.0.6 on 2023-01-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0047_alter_cart_product_alter_cart_user_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(to='techcart.product'),
        ),
    ]
