# Generated by Django 4.0.6 on 2023-01-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0048_remove_cart_product_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
