# Generated by Django 4.0.6 on 2023-01-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0053_remove_product_rating_product_rev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rev',
        ),
    ]
