# Generated by Django 3.2.16 on 2023-01-25 17:22

from django.db import migrations, models
import techcart.models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0054_remove_product_rev'),
    ]

    operations = [
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.TextField()),
                ('gpu', models.TextField()),
                ('ram', models.TextField()),
                ('storage', models.TextField()),
                ('image', models.ImageField(null=True, upload_to=techcart.models.upload_to)),
            ],
        ),
    ]
