# Generated by Django 3.2.16 on 2023-01-26 12:53

from django.db import migrations, models
import django.db.models.deletion
import techcart.models


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0055_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='techcart.pc'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=techcart.models.upload_to),
        ),
    ]
