# Generated by Django 3.2.16 on 2023-01-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techcart', '0056_auto_20230126_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pc',
        ),
        migrations.DeleteModel(
            name='PC',
        ),
    ]
